# Generated by Django 3.1.7 on 2021-03-31 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('maadmin', models.FloatField(primary_key=True, serialize=False)),
                ('tenadmin', models.CharField(max_length=255)),
                ('sdtadmin', models.CharField(max_length=10, unique=True)),
                ('emailadmin', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banggia',
            fields=[
                ('hanguutien', models.FloatField(primary_key=True, serialize=False)),
                ('goituan', models.FloatField()),
                ('gia', models.FloatField()),
            ],
            options={
                'db_table': 'banggia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capbac',
            fields=[
                ('macapbac', models.FloatField(primary_key=True, serialize=False)),
                ('tencapbac', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'capbac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chuyennganh',
            fields=[
                ('machuyennganh', models.FloatField(primary_key=True, serialize=False)),
                ('tenchuyennganh', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chuyennganh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Congty',
            fields=[
                ('macongty', models.FloatField(primary_key=True, serialize=False)),
                ('tencongty', models.CharField(max_length=255, unique=True)),
                ('motacongty', models.TextField(blank=True, null=True)),
                ('diachict', models.CharField(max_length=255)),
                ('quymonhansu', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.BinaryField()),
                ('dienthoai', models.CharField(max_length=10, unique=True)),
                ('website', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'congty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hinhthuclamviec',
            fields=[
                ('mahtlamviec', models.FloatField(primary_key=True, serialize=False)),
                ('tenhinhthuclamviec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hinhthuclamviec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hocvanbangcap',
            fields=[
                ('mahvbc', models.FloatField(primary_key=True, serialize=False)),
                ('tenbangcapchungchi', models.CharField(max_length=255)),
                ('tentruong', models.CharField(blank=True, max_length=255, null=True)),
                ('xeploai', models.FloatField(blank=True, null=True)),
                ('thoigianbatdaunh', models.DateField(blank=True, null=True)),
                ('thoigianketthuc', models.DateField(blank=True, null=True)),
                ('thongtinbosung', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hocvanbangcap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kinhnghiemlamviec',
            fields=[
                ('makinhnghiem', models.FloatField(primary_key=True, serialize=False)),
                ('tencongviectunglam', models.CharField(max_length=255)),
                ('thoigianbd', models.DateField()),
                ('thoigiankt', models.DateField()),
                ('motacv', models.TextField(blank=True, null=True)),
                ('tencongtytunglamviec', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kinhnghiemlamviec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kynang',
            fields=[
                ('makynang', models.FloatField(primary_key=True, serialize=False)),
                ('tenkynang', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kynang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaikynang',
            fields=[
                ('maloaikynang', models.FloatField(primary_key=True, serialize=False)),
                ('tenloaikynang', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'loaikynang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mucluong',
            fields=[
                ('mamucluong', models.FloatField(primary_key=True, serialize=False)),
                ('tu', models.FloatField()),
                ('den', models.FloatField()),
            ],
            options={
                'db_table': 'mucluong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nguoithamkhao',
            fields=[
                ('manguoithamkhao', models.FloatField(primary_key=True, serialize=False)),
                ('tenntk', models.CharField(max_length=255)),
                ('sdtntk', models.CharField(max_length=10, unique=True)),
                ('emailntk', models.CharField(max_length=255, unique=True)),
                ('tencongtyntk', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nguoithamkhao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieudanhgia',
            fields=[
                ('sophieudanhgia', models.FloatField(primary_key=True, serialize=False)),
                ('ngaydanhgia', models.DateField()),
            ],
            options={
                'db_table': 'phieudanhgia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieuthanhtoan',
            fields=[
                ('sophieuthanhtoan', models.FloatField(primary_key=True, serialize=False)),
                ('ngaythanhtoan', models.DateField()),
            ],
            options={
                'db_table': 'phieuthanhtoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieuungtuyen',
            fields=[
                ('sophieuungtuyen', models.FloatField(primary_key=True, serialize=False)),
                ('vitriungtuyen', models.CharField(max_length=255)),
                ('sonamkinhnghiem', models.CharField(blank=True, max_length=50, null=True)),
                ('muctieunghenghiep', models.TextField(blank=True, null=True)),
                ('kynangchuyenmon', models.TextField(blank=True, null=True)),
                ('ngayungtuyen', models.DateField(blank=True, null=True)),
                ('ngayphongvan', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phieuungtuyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quanhuyen',
            fields=[
                ('maquanhuyen', models.FloatField(primary_key=True, serialize=False)),
                ('tenquanhuyen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quanhuyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('taikhoan', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tieuchi',
            fields=[
                ('matieuchi', models.FloatField(primary_key=True, serialize=False)),
                ('tentieuchi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tieuchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tintuyendung',
            fields=[
                ('matintuyendung', models.FloatField(primary_key=True, serialize=False)),
                ('tencongviectd', models.CharField(max_length=255)),
                ('mota', models.TextField()),
                ('quyenloiduochuong', models.TextField()),
                ('yeucaucongviec', models.TextField()),
                ('yeucauhoso', models.TextField()),
                ('hannophoso', models.DateField()),
                ('yeucaukinhnghiem', models.TextField()),
                ('soluongtuyen', models.FloatField()),
                ('yeucaugioitinh', models.FloatField(blank=True, null=True)),
                ('tennguoilienhe', models.CharField(blank=True, max_length=255, null=True)),
                ('sdtnlh', models.CharField(blank=True, max_length=10, null=True)),
                ('emailnlh', models.CharField(blank=True, max_length=255, null=True)),
                ('ngonnguhoso', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tintuyendung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trinhdohocvan',
            fields=[
                ('matrinhdohocvan', models.FloatField(primary_key=True, serialize=False)),
                ('tentrinhdohocvan', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trinhdohocvan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ungvien',
            fields=[
                ('maungvien', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotenuv', models.CharField(max_length=255)),
                ('sdtuv', models.CharField(max_length=10, unique=True)),
                ('emailuv', models.CharField(max_length=255, unique=True)),
                ('ngaysinhuv', models.DateField(blank=True, null=True)),
                ('quoctich', models.CharField(blank=True, max_length=255, null=True)),
                ('diachiungvien', models.CharField(blank=True, max_length=255, null=True)),
                ('gioitinh', models.FloatField(blank=True, null=True)),
                ('tinhtranghonnhan', models.FloatField(blank=True, null=True)),
                ('anhdaidien', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ungvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietdanhgia',
            fields=[
                ('matieuchi', models.OneToOneField(db_column='matieuchi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TuyenDung.tieuchi')),
                ('diem', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chitietdanhgia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietthanhtoan',
            fields=[
                ('sophieuthanhtoan', models.OneToOneField(db_column='sophieuthanhtoan', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TuyenDung.phieuthanhtoan')),
                ('sotien', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chitietthanhtoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kynangquantrong',
            fields=[
                ('matintuyendung', models.OneToOneField(db_column='matintuyendung', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TuyenDung.tintuyendung')),
            ],
            options={
                'db_table': 'kynangquantrong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trinhdokynang',
            fields=[
                ('maungvien', models.OneToOneField(db_column='maungvien', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TuyenDung.ungvien')),
                ('trinhdokynang', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trinhdokynang',
                'managed': False,
            },
        ),
    ]
